# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35fdbb676fdc9172bd3c02f58966c3e2136402d1edf452cd206980e665421402096e96ea0a0a6f0adfdd3f040e891fe7056df0d05505e8bf29ced63093cd2a90

test:
  secret_key_base: 5368072f203e4bd0334b55471746d1341284afc77309a2070b63bea3c658bb2a7445debddf9828c2b77e0cf7ac5dfe93e4eb250388205a701d82b17374f48b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
